import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import styles from './page.module.scss'
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="root">
          <header>
            <div className={styles.container}>
              <div className={styles.header_inner}>
                <nav>
                  <Link href={"/about/getting-started"}>Layout</Link>
                  <Link href={"/team"}>Template</Link>
                  <Link href={"/about/admin"}>Admin</Link>
                </nav>
              </div>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
